---
- block:
  # When the IPA images are on a different folder we have to link it
  - name: Create links to IPA image/kernel in the tfpboot folder
    file:
      path: "{{ ironic_pxe_tftp_root }}/{{ item }}"
      src:  "{{ ironic_deploy_http_root }}/{{ item }}"
      owner: "{{ ironic_user }}"
      group: "{{ ironic_group }}"
      state: link
    with_items:
      - "{{ ironic_pxe_ipa_img_name }}"
      - "{{ ironic_pxe_ipa_kernel_name }}"
    when: ironic_inspector_enabled and ironic_pxe_ipa_download

  - name: Delete links to IPA image/kernel in the tfpboot folder
    file:
      path: "{{ ironic_pxe_tftp_root }}/{{ item }}"
      state: absent
    with_items:
      - "{{ ironic_pxe_ipa_img_name }}"
      - "{{ ironic_pxe_ipa_kernel_name }}"
    when: not ironic_inspector_enabled and ironic_pxe_ipa_download

  # When the tinyIPA images are on a different folder we have to link it
  - name: Create links to tiny IPA image/kernel in the tfpboot folder
    file:
      path: "{{ ironic_pxe_tftp_root }}/{{ item }}"
      src:  "{{ ironic_deploy_http_root }}/{{ item }}"
      owner: "{{ ironic_user }}"
      group: "{{ ironic_group }}"
      state: link
    with_items:
      - "{{ ironic_pxe_tinyipa_img_name }}"
      - "{{ ironic_pxe_tinyipa_kernel_name }}"
    when: ironic_inspector_enabled and ironic_pxe_tinyipa_download

  - name: Delete links to tiny IPA image/kernel in the tfpboot folder
    file:
      path: "{{ ironic_pxe_tftp_root }}/{{ item }}"
      state: absent
    with_items:
      - "{{ ironic_pxe_tinyipa_img_name }}"
      - "{{ ironic_pxe_tinyipa_kernel_name }}"
    when: not ironic_inspector_enabled and ironic_pxe_tinyipa_download

  - name: Create tftproot pxelinux.cfg folder
    file:
      path: "{{ ironic_pxe_tftp_root }}/pxelinux.cfg"
      owner: "{{ ironic_user }}"
      group: "{{ ironic_group }}"
      mode: 0775
      state: directory

  - name: Generate pxelinux.cfg/default
    template:
      src: pxelinux_default.j2
      dest: "{{ ironic_pxe_tftp_root }}/pxelinux.cfg/default"
      owner: "{{ ironic_user }}"
      group: "{{ ironic_group }}"
      mode: 0664
    when: ironic_inspector_enabled

  - name: Delete pxelinux.cfg/default
    file:
      dest: "{{ ironic_pxe_tftp_root }}/pxelinux.cfg/default"
      state: absent
    when: not ironic_inspector_enabled

  when: >
    ironic_pxe_tftp_root is defined
    and ironic_pxe_tftp_root

